### PR TITLE
fix: memory leak from keys (issue 41)

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/TeskaLabs/cysimdjson/issues/41

credit: @TkTech

### CODE REVIEW

**Comment by ateska** [comment]
@PremyslCerny can you please check.

**Comment by TkTech** [comment]
I'm fairly confident this is an issue in a couple more places, just less severe. The same pattern of casting to object is used in other places.

**Comment by ateska** [comment]
@TkTech I agree, it is scheduled to be investigated and fixed.

**Comment by hz61p1** [comment]
@ateska Any news on when this will be reviewed?

**Comment by ateska** [comment]
I'll check that soon, sorry, family troubles come first.

**Pull request merged**
